// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dydmtschudgchuxnpzel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZG10c2NodWRnY2h1eG5wemVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTU3NjgsImV4cCI6MjA2MTE3MTc2OH0.yB361tg4Q2-3UvdpTMuddWY8jMhJKnsbSB_Ocuj056g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);